class flightLocators:
    title_of_the_page_to_book_flight = "MakeMyTrip - #1 Travel Website 50% OFF on Hotels, Flights & Holiday"
    flight_option_xpath = "//span[@class='chNavText darkGreyText'][1]"
    round_trip_radio_button_select = "//li[contains(text(),'Round Trip')]"
    from_City_id = "fromCity"
    from_text_box_xpath = "//input[@placeholder='From']"
    selection_in_from_field_xpath = "//p[text()='Jaipur, India']"
    to_city_xpath = "//input[@placeholder='To']"
    select_to_city_from_list_xpath = "//p[text()='Bangkok, Thailand']"
    Departure_xpath = "//span[contains(text(),'DEPARTURE')]"
    Departure_date_xpath = "//body[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[2]/div[7]/div[1]/p[1]"
    # departure_date_xpath = "//div[@class='DayPicker-Day' or @aria-label='Sat Jul 10 2021' and @aria-selected='false']"
    # select_departure_date_xpath = "//div[@class='DayPicker-Day'][3]"
    # from_month_xpath = "//div[@class='DayPicker-Month']"
    # expected_fr_date = '10'
    # from_date_xpath = "//td[not(contains(@class,'DayPicker-Month'))]/a[text()='' + expected_fr_date + '']"
    Return_xpath = "//span[contains(text(),'RETURN')]"
    return_date_xpath = "//body[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[3]/div[3]/div[1]/p[1]"
    # select_return_date_xpath = "//div[@class='DayPicker-Day DayPicker-Day--selected'][3]"
    travellers_xpath = "//span[contains(text(),'Travellers & CLASS')]"
    no_of_adults_xpath = "//li[@data-cy='adults-4']"
    no_of_children_xpath = "//li[@data-cy='children-1']"
    no_of_infants_xpath = "//li[@data-cy='infants-1']"
    travel_class_xpath = "//li[text()='Premium Economy']"
    apply_button_xpath = "//button[text()='APPLY']"
    search_button_xpath = "//a[text()='Search']"
    search_not_found_xpath = "//p[text()='No flights found']"
    go_back_button_xpath = "//button[text()='Go Back']"
